"""Study-pack rendering: one evidence record plus its session, as markdown.

Stdlib-only and deterministic (no wall clock, no randomness). Serves Study A's
"rendered example evidence trace" and Study B's record-plus-log-excerpt
(docs/EXPERT-STUDY-PROTOCOL.md). Presentation only: the canonical evidence
artefact remains the chained JSONL; nothing rendered here enters any hash.
"""

from __future__ import annotations

import json
from typing import TYPE_CHECKING

from auditors_trace.constraints.templates import build_index
from auditors_trace.model.ocel_schema import Qualifier

if TYPE_CHECKING:
    from collections.abc import Sequence

    from auditors_trace.evidence.record import EvidenceRecord
    from auditors_trace.model.log import OCELLog


def session_excerpt(log: OCELLog, session_id: str, cited_event_ids: Sequence[str]) -> str:
    """The session's events as a markdown table, cited rows marked.

    An event belongs to the excerpt if any of its relations reference the
    session object (``within`` for ordinary events, ``declares`` for the
    session_start that opens it). Key relations shown are the semantic ones —
    ``declares`` materialisation and the ``within`` plumbing are elided.
    """
    index = build_index(log)
    cited = set(cited_event_ids)
    rows = ["| Event | Time (UTC) | Type | Key relations | Cited |", "|---|---|---|---|---|"]
    found = False
    for event in index.events:
        if not any(relation.object_id == session_id for relation in event.relations):
            continue
        found = True
        relations = "; ".join(
            f"{relation.qualifier.value} -> {relation.object_id}"
            for relation in event.relations
            if relation.qualifier not in (Qualifier.DECLARES, Qualifier.WITHIN)
        )
        marker = "**<-- cited**" if event.event_id in cited else ""
        rows.append(
            f"| `{event.event_id}` | {event.timestamp} | {event.event_type.value} "
            f"| {relations or '(declarations only)'} | {marker} |"
        )
    if not found:
        raise ValueError(f"no events reference session {session_id!r}")
    return "\n".join(rows)


def study_pack_markdown(record: EvidenceRecord, log: OCELLog, *, source_label: str = "") -> str:
    """One rendered example evidence trace: the record, then its session.

    ``source_label`` carries the caller's provenance line (which split, which
    crosswalk); the function itself adds nothing time- or environment-bound.
    """
    index = build_index(log)
    first_cited = record.evidence.ocel_event_ids[0]
    session_id = index.session_of_event.get(first_cited)
    if session_id is None:
        raise ValueError(f"cited event {first_cited!r} has no session in this log")

    display = json.dumps(
        record.model_dump(mode="json", by_alias=True, exclude_none=True),
        indent=2,
        sort_keys=True,
        ensure_ascii=False,
    )
    excerpt = session_excerpt(log, session_id, record.evidence.ocel_event_ids)
    provenance = source_label or "generated by `python -m auditors_trace.cli pack`"

    return f"""# Evidence record example

> Provenance: {provenance}

## What this record claims

**{record.constraint.id}** — {record.constraint.natural_language}

Severity **{record.severity.value}**. The record cites the exact events and
telemetry spans the finding rests on, the legal basis it traces to, and a
rerun command: executing

```
{record.reproducibility.rerun_command}
```

over the pinned artefacts re-derives this record byte-for-byte. Records are
hash-chained and tamper-evident: any change to any field breaks verification.

## The evidence record

```json
{display}
```

## The session, as recorded

Session `{session_id}` in full; the rows marked below are the events this
record cites as evidence.

{excerpt}
"""
